version: "2"
plugins:
  rubocop:
    enabled: true
    config:
      file: .rubocop.yml
  brakeman:
    enabled: true
    config:
      file: .brakeman.yml # not supported
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  rubymotion:
    enabled: true
  stylelint:
    enabled: true
exclude_patterns:
- bin/**/*
- private/**/*
- public/**/*
- spec/**/*
- "**/vendor/**/*"
