runner:
  rubocop:
    cmd: bundle exec rubocop
    format: rubocop
  brakeman:
    cmd: bundle exec brakeman --quiet --format tabs
    format: brakeman
  stylelint:
    cmd: .github/workflows/stylelint.sh
    errorformat:
      - "%f:%l:%c:%t%*[^:]: %m"
  eslint:
    cmd: eslint --resolve-plugins-relative-to=$(npm root -g) -f eslint-formatter-rdjson.js 'app/assets/**/*.{js,js.erb}'
    format: rdjson
