runner:
  rubocop:
    cmd: bundle exec rubocop
    format: rubocop
  brakeman:
    cmd: bundle exec brakeman --quiet --format tabs
    format: brakeman
  stylelint:
    cmd: npx stylelint --no-color '{app,db}/**/*.{css,scss,sass}'
    format: stylelint
  eslint:
    cmd: npx eslint --no-color -f stylish 'app/**/*.{js,js.erb}' 'db/**/*.{js,js.erb}'
    format: eslint
