runner:
  rubocop:
    cmd: bundle exec rubocop
    format: rubocop
  brakeman:
    cmd: bundle exec brakeman --quiet --format tabs
    format: brakeman
  stylelint:
    cmd: .github/workflows/stylelint.sh
    errorformat:
      - "%f:%l:%c:%t%*[^:]: %m"
  eslint:
    cmd: npx eslint -f stylish 'app/assets/**/*.{js,js.erb}' 'app/javascript/**/*.js'
    format: eslint
