runner:
  rubocop:
    cmd: bundle exec rubocop
    format: rubocop
  brakeman:
    cmd: bundle exec brakeman --quiet --format tabs
    format: brakeman
  "scss-lint":
    cmd: bundle exec scss-lint
    errorformat:
      - "%f:%l:%c %m"
  erblint:
    cmd: bundle exec erblint --format compact app/views
    errorformat:
      - "%f:%l:%c: %m"
