inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - Guardfile
    - Vagrantfile
    - ",memo/*"
    - bin/*
    - vendor/bundle/**/*

Rails:
  Enabled: true

# Cop supports --auto-correct.
Rails/Output:
  Enabled: false

# Configuration parameters: AlignWith, SupportedStyles.
Lint/DefEndAlignment:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BarePercentLiterals:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/PercentQLiterals:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Enabled: true

# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Enabled: true

# Cop supports --auto-correct.
Style/UnneededPercentQ:
  Enabled: true

Lint/RescueException:
  Enabled: false
