class SS::Site
  include SS::Model::Site
  include SS::Relation::File
  include SS::Addon::MobileSetting
  include SS::Addon::MapSetting
  include SS::Addon::KanaSetting
  include SS::Addon::OpenGraphSetting
  include SS::Addon::FacebookSetting
  include SS::Addon::TwitterSetting
  include SS::Addon::LineSetting
  include SS::Addon::FileSetting
  include SS::Addon::MailSetting
  include SS::Addon::TrashSetting
  include SS::Addon::ApproveSetting
  include Opendata::Addon::SiteSetting
  include SS::Addon::EditorSetting
  include Cms::Addon::LogoSetting
  include SS::Addon::Elasticsearch::SiteSetting
  include SS::Addon::Translate::SiteSetting
  include SS::Addon::PartnerSetting
  include SS::Addon::InquirySetting
  include SS::Addon::CheckLinksSetting
  include SS::Addon::WorkflowSetting
  include SS::Addon::SourceCleaner::SiteSetting
  include SS::Addon::SiteUsage
  include SS::Addon::GenerateLock
  include SS::Addon::MaintenanceMode
  include SS::Ldap::SiteSetting
  include Chorg::SiteSetting
end
