# mongodb configuration
# if you want to know about detail configuration,
# see: https://docs.mongodb.org/ecosystem/tutorial/mongoid-installation/#mongoid-configuration
production:
  sessions:
    default:
      database: ss
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: ss_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary

development:
  sessions:
    default:
      database: ss
      hosts:
        - localhost:27017
