# Fuseki Server

production: &production
  # SPARQL Endpoint
  fuseki:
    disable: true
    host: 127.0.0.1
    port: 3030
    dataset: opendata

  # Web API
  api:
    package_list_help: "Help: package_list"
    group_list_help:  "Help: group_list"
    tag_list_help: "Help: tag_list"
    package_show_help: "Help: package_show"
    tag_show_help: "Help: tag_show"
    group_show_help:   "Help: group_show"

test:
  <<: *production

development:
  <<: *production
