# secrets configuration

# Make sure the secret is at least 30 characters and all random,
# Use `rake secret`.

production: &production
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: dbcae379048ebb545900e67e5e3c6c3a8a74428f6a436d3113a83ff12a1c05368281c9b2eeb8414d7abe184843b7103034090c16a46fd0159cf764787d499a54

test:
  <<: *production

development:
  <<: *production
