name: "shirasagi-devcontainer"

services:
  shirasagi:
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/shirasagi:cached
    command: sleep infinity # 開発コンテナが勝手にダウンしない為に設定する
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db:database
  db:
    image: mongo:7.0
    env_file:
      - ../.env
    volumes:
      - db_data:/data/db
    ports:
      - 27017:27017

volumes:
  db_data: {}
