# event

production: &production
  # Max Number of Event Term
  max_term_form: 10

  # Use Basic Authentication when import ics
  basic_authentication: false

test:
  <<: *production

development:
  <<: *production
