# kana

production: &production
  disable: false
  #root: Rails.root.to_s
  location: /kana
  mecab_indexer: /usr/local/libexec/mecab/mecab-dict-index
  mecab_dicdir: /usr/local/lib/mecab/dic/ipadic
  converter:
    kana-marks: [ "write-kana", "end-write-kana" ]
    skip-marks: [ "skip-kana", "end-skip-kana" ]
  skip_attributes:
    a:
      - href
    area:
      - href
    audio:
      - src
    base:
      - href
    embed:
      - src
    iframe:
      - src
    img:
      - src
    input:
      - src
    link:
      - href
    script:
      - src
    source:
      - src
    video:
      - src

test:
  <<: *production

development:
  <<: *production
