production: &production
  # set OAuth id and secret pairs you want to activate.
  twitter_client_id:
  twitter_client_secret:
  facebook_client_id:
  facebook_client_secret:
  yahoojp_client_id:
  yahoojp_client_secret:
  yahoojp_v2_client_id:
  yahoojp_v2_client_secret:
  google_oauth2_client_id:
  google_oauth2_client_secret:
  github_client_id:
  github_client_secret:

test:
  <<: *production

development:
  <<: *production
