# open_uri_proxy

production: &production
  disable: true
  proxy_http_basic_authentication:
    proxy_uri: "http://localst:8080"
    proxy_username: "username"
    proxy_password: "password"

test:
  <<: *production

development:
  <<: *production
