production: &production
  # specify which group should be logged in.
  login_group: シラサギ市

  # without csrf token ( /.mypage/remote_login )
  remote_login: false

  # Redirects the page after login.
  logged_in_page: /.mypage

  # Session Lifetime in seconds
  session_lifetime: 1800

  # trusted_urls are list of external url which can transfer without confirmation
  trusted_urls: []

test:
  <<: *production

development:
  <<: *production

  # Session Lifetime in seconds
  session_lifetime: 3600
