# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby-3.4

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  DISABLE_SPRING: 1

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 50
    strategy:
      fail-fast: false
      matrix:
        parallelism: [ 1 ]
        id: [ 0 ]
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          # 削除するものに true を、削除しないものに false をセットする
          #
          # 注意：
          # 当然、空き容量はあればあるほど良いが、true の数を多くすればするほどテストの実行時間が長くなる
          # すべてを true にすると、1並列当たり3分ぐらいかかる。6並列だと18分、10並列だと30分もかかる
          # テストが完了する最低限の空きがあれば十分なので、true にするのもほどほどに
          tool-cache: false
          android: false # trueにすると11GiBの削減
          dotnet: false # trueにすると5.1GiBの削減
          haskell: true # trueにすると3.6GiBの削減
          large-packages: false
          docker-images: false
          swap-storage: false
      - uses: actions/checkout@v7
      - name: Generate ja_JP.UTF-8
        run: |
          sudo locale-gen ja_JP
          sudo update-locale LANG=ja_JP.UTF-8
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.1
        with:
          mongodb-version: 8.0
      - name: Prepare Ldap
        run: docker pull osixia/openldap
      - name: Prepare Shirasagi Mail
        run: |
          docker pull ghcr.io/shirasagi/mail:latest
          docker tag ghcr.io/shirasagi/mail:latest shirasagi/mail:latest
      - name: Launch Shirasagi Mail
        run: |
          docker run --name test_mail -d -p 10143:143 -p 10587:587 shirasagi/mail
      - name: Prepare Michecker
        run: |
          docker pull ghcr.io/shirasagi/michecker:latest
          docker tag ghcr.io/shirasagi/michecker:latest shirasagi/michecker:latest
      - name: Elasticsearch Docker Image Digest
        id: elasticsearch-docker-image-hash
        run: |
          digest=$(docker manifest inspect ghcr.io/shirasagi/elasticsearch:8 | jq -r .config.digest | sed -e 's/^.*://')
          echo $digest
          echo "DIGEST=$digest" >> $GITHUB_OUTPUT
      - name: Cache Elasticsearch Docker image
        uses: actions/cache@v6
        id: cache-elasticsearch-images
        with:
          path: ~/docker-elasticsearch-image
          key: ${{ runner.os }}-elasticsearch-docker-image-${{ steps.elasticsearch-docker-image-hash.outputs.DIGEST }}
      - name: Prepare Elasticsearch
        if: steps.cache-elasticsearch-images.outputs.cache-hit != 'true'
        run: |
          docker pull ghcr.io/shirasagi/elasticsearch:8
          docker tag ghcr.io/shirasagi/elasticsearch:8 shirasagi/elasticsearch:latest
          docker save shirasagi/elasticsearch:latest -o ~/docker-elasticsearch-image
      - name: Load Elasticsearch
        if: steps.cache-elasticsearch-images.outputs.cache-hit == 'true'
        run: |
          docker load -i ~/docker-elasticsearch-image
      - name: Launch Elasticsearch
        id: elasticsearch
        run: |
          container_id=$(docker run -d --name elasticsearch -p 9200:9200 -e discovery.type=single-node -e xpack.security.enabled=false -e xpack.security.http.ssl.enabled=false shirasagi/elasticsearch)
          if [ $? -ne 0 ]; then
            exit $?
          fi
          echo $container_id
          echo "CONTAINER_ID=$container_id" >> $GITHUB_OUTPUT
      - name: Ckan Docker Image Digest
        id: ckan-docker-image-hash
        run: |
          digest=$(docker manifest inspect ghcr.io/shirasagi/ckan:latest | jq -r .config.digest | sed -e 's/^.*://')
          echo $digest
          echo "DIGEST=$digest" >> $GITHUB_OUTPUT
      - name: Cache Ckan Docker image
        uses: actions/cache@v6
        id: cache-ckan-images
        with:
          path: ~/docker-ckan-image
          key: ${{ runner.os }}-ckan-docker-image-${{ steps.ckan-docker-image-hash.outputs.DIGEST }}
      - name: Prepare Ckan
        if: steps.cache-ckan-images.outputs.cache-hit != 'true'
        run: |
          docker pull ghcr.io/shirasagi/ckan:latest
          docker tag ghcr.io/shirasagi/ckan:latest shirasagi/ckan:latest
          docker save shirasagi/ckan:latest -o ~/docker-ckan-image
      - name: Load Ckan
        if: steps.cache-ckan-images.outputs.cache-hit == 'true'
        run: |
          docker load -i ~/docker-ckan-image
      - name: Launch Ckan
        id: ckan
        run: |
          container_id=$(docker run -d --name ckan -p 8080:80 shirasagi/ckan)
          if [ $? -ne 0 ]; then
            exit $?
          fi
          echo $container_id
          echo "CONTAINER_ID=$container_id" >> $GITHUB_OUTPUT
      - name: Install pre requisites
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: imagemagick libmagick++-dev sox libsox-dev lame libmp3lame-dev mecab libmecab-dev mecab-ipadic-utf8 open-jtalk open-jtalk-mecab-naist-jdic graphicsmagick
          version: 1.0
      - name: Google Chrome Version
        run: |
          which google-chrome
          /usr/bin/google-chrome --version
        continue-on-error: true
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'yarn'
      - name: Install node modules
        run: yarn install --frozen-lockfile
      - name: Install MeCab Ruby
        run: |
          tar xzf vendor/mecab/mecab-ruby-0.996.tar.gz
          cd mecab-ruby-0.996 && bundle exec ruby extconf.rb && make && sudo make install
      #    - name: Prepare Assets
      #      run: bash .travis.d/exec.sh before_script 05-bin-deploy
      - name: Prepare Config
        run: bash .travis.d/exec.sh before_script 10-copy-config
      - name: Prepare kana.yml
        run: |
          cp config/defaults/kana.yml config/
          sed -i "s#/usr/local/libexec/mecab/mecab-dict-index#/usr/lib/mecab/mecab-dict-index#" config/kana.yml
          sed -i "s#/usr/local/lib/mecab/dic/ipadic#/usr/share/mecab/dic/ipadic#" config/kana.yml
          diff -u config/defaults/kana.yml config/kana.yml || true
      - name: Prepare voice.yml
        run: |
          cp config/defaults/voice.yml config/
          sed -i "s#/usr/local/bin/open_jtalk#/usr/bin/open_jtalk#" config/voice.yml
          sed -i "s#/usr/local/dic#/var/lib/mecab/dic/open-jtalk/naist-jdic#" config/voice.yml
          sed -i "s#/usr/local/bin/sox#/usr/bin/sox#" config/voice.yml
          sed -i "s#/usr/local/bin/lame#/usr/bin/lame#" config/voice.yml
          diff -u config/defaults/voice.yml config/voice.yml || true
      - name: Prepare ImageMagick-6 policy
        run: |
          cd /etc/ImageMagick-6
          sudo sed -i "s#<policy domain=\"coder\" rights=\"none\" pattern=\"PDF\" />#<policy domain=\"coder\" rights=\"read\" pattern=\"PDF\" />#" policy.xml
          echo "### /etc/ImageMagick-6/policy.xml ###"
          cat policy.xml
      - name: Running Docker Containers
        run: docker ps -a
      - name: Bundle assets
        run: npx webpack-cli build
#      - name: Run tests
#        run: |
#          file_list=$(bundle exec ruby .travis.d/split_specs.rb -p 12 -i 1)
#          if [ $? -ne 0 ]; then
#            exit 1
#          fi
#          echo $file_list | xargs bundle exec rspec --profile 10
#        env:
#          TZ: "Asia/Tokyo"
#          LANG: ja_JP.UTF-8
#          LC_ALL: ja_JP.UTF-8
#          allow_open_jtalk: 1
#          LDAP_TEST: enable
#          ES_CONTAINER_ID: ${{ steps.elasticsearch.outputs.CONTAINER_ID }}
#          CKAN_CONTAINER_ID: ${{ steps.ckan.outputs.CONTAINER_ID }}
#          RUBYOPT: "-W:deprecated"
#          logs_on_failure: 0
#          CAPYBARA_MAX_WAIT_TIME: 30
#          DOWNLOAD_MAX_WAIT_TIME: 10
#          driver: chrome
#          # driver: firefox
#          # driver: random
#          # RSPEC_LOCALE: en
#          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
#          RUBYZIP_V3_API_WARN: true
      #CI実行中にElasticsearchに問題が発生した場合、
      #このステップを有効にしElasticsearchのログを確認すること
      #- name: After test
      #  if: always()
      #  run: |
      #    echo "curl -i http://localhost:9200"
      #    curl -i http://localhost:9200 || true
      #    echo "curl -i http://localhost:9200/_cluster/health"
      #    curl -i http://localhost:9200/_cluster/health || true
      #    echo "docker logs elasticsearch"
      #    docker logs elasticsearch | tail
